PTin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('trainer.urls')),
    path('', include('accounts.urls')),
    path('', include('review.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# def protected_files(request, path, document_root=None):
#     messages.error(request, "접근 불가")
#     return redirect('/')
#
#
# urlpatterns += static(settings.MEDIA_URL, protected_files, document_root=settings.MEDIA_ROOT)

trainer/urls.py
from django.urls import path
from . import views


# index, trainer list
urlpatterns = [
    path('', views.index, name='index'),
    path('trainers/', views.TrainerListView.as_view(), name='trainers'),
    path('trainer/<int:pk>', views.trainer_detail_view, name='trainer-detail'),
    path('lectures/', views.LectureListView.as_view(), name='lectures'),
    path('lecture/<int:pk>', views.LectureDetailView.as_view(), name='lecture-detail'),
]

urlpatterns += [
    path('aboutus/', views.aboutus, name='aboutus'),
]

# my class
urlpatterns += [
    path('traineelectures/', views.LecturesByUserListView.as_view(), name='trainee-lectures'),
    path('trainerlectures/', views.LecturesByTrainerListView.as_view(), name='trainer-lectures'),
]

# Register, modify, delete trainer
urlpatterns += [
    path('trainer/new/', views.trainer_new, name='trainer-new'),
    path('trainer/<int:trainer_id>/update/', views.trainer_update, name='trainer-update'),
    path('trainer/<int:trainer_id>/delete/', views.trainer_delete, name='trainer-delete')
]

# Search
urlpatterns += [
    path('search/', views.trainer_search, name='search'),
]

urlpatterns += [
    path('accounts/mypage/mylist/', views.trainer_mylist, name='trainer-mylist'),
]

trainer/models.py
import os
import re

from django.db import models
from django.urls import reverse
import uuid
from datetime import datetime
from accounts.models import User

from PTin import settings

from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill, Resize


class Genre(models.Model):
    """Model representing a book genre."""
    name = models.CharField(max_length=200, help_text='Enter a class genre (e.g. PT, yoga, pilates')

    def __str__(self):
        """String for representing the Model object."""
        return self.name


class Hashtag(models.Model):
    """Model representing a hashtag"""
    name = models.CharField(max_length=20, unique=True, help_text='Enter a feature of trainer.')

    def __str__(self):
        """String for representing the Model object"""
        return self.name


def get_file_path(instance, filename):
    ymd_path = datetime.now().strftime('%Y/%m/%d')
    uuid_name = uuid.uuid4().hex
    return '/'.join(['upload_file/', ymd_path, uuid_name])


def get_profile_image_path(instance, filename):
    ymd_path = datetime.now().strftime('%Y/%m/%d')
    uuid_name = uuid.uuid4().hex
    return '/'.join(['profile/', ymd_path, uuid_name])


class Trainer(models.Model):
    """Model representing a trainer (not a specific class)"""
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.CASCADE, verbose_name='작성자')
    name = models.CharField(max_length=10, verbose_name='이름')
    genretext = models.CharField(max_length=200, null=True)
    genre = models.ManyToManyField(Genre, blank=True, verbose_name='장르')
    address = models.CharField(max_length=40, null=True, verbose_name='지역')
    place = models.CharField(max_length=40, null=True, verbose_name='장소')
    summary = models.TextField(null=True, blank=True)
    tagtext = models.CharField(max_length=200, null=True, blank=True)
    hashtag = models.ManyToManyField(Hashtag, blank=True)
    # upload_files = models.FileField(upload_to=get_file_path, null=True, blank=True, verbose_name='파일')
    # filename = models.CharField(max_length=64, null=True, verbose_name='첨부파일명')
    image = ProcessedImageField(
        upload_to=get_profile_image_path, processors=[ResizeToFill(width=500, height=500, upscale=False)],
        null=True, blank=True,
        format='JPEG', options={'quality': 90}, verbose_name="프로필 이미지"
    )
    imagename = models.CharField(max_length=64, null=True, blank=True, verbose_name='이미지파일')

    # Certificate
    cert1, cert2, cert3, cert4, cert5, cert6, cert7, cert8, cert9, cert10 = [
        models.CharField(max_length=40, null=True, blank=True) for i in range(10)
    ]
    certimg1, certimg2, certimg3, certimg4, certimg5, certimg6, certimg7, certimg8, certimg9, certimg10 = [
        ProcessedImageField(
            upload_to=get_profile_image_path, processors=[Resize(width=500, height=None, upscale=False)],
            null=True, blank=True, format='JPEG', options={'quality': 90}
        ) for i in range(10)
    ]
    # cert = [cert1, cert2, cert3, cert4, cert5, cert6, cert7, cert8, cert9, cert10]
    # certimg = [certimg1, certimg2, certimg3, certimg4, certimg5, certimg6, certimg7, certimg8, certimg9, certimg10]

    sns1, sns2, sns3, sns4, sns5 = [
        models.CharField(max_length=256, null=True, blank=True) for i in range(5)
    ]

    def hashtag_save(self):
        self.hashtag.set([])
        hashtags = re.findall(r'#(\w+)\b', self.tagtext)

        if not hashtags:
            return

        for tag in hashtags:
            tag, tag_created = Hashtag.objects.get_or_create(name=tag)
            self.hashtag.add(tag)

    def genre_save(self):
        self.genre.set([])
        genres = re.findall(r'(\w+)\b', self.genretext)

        if not genres:
            return

        for tag in genres:
            tag, tag_created = Genre.objects.get_or_create(name=tag)
            self.genre.add(tag)

    def __str__(self):
        """String for representing the Model object."""
        return self.name

    def get_absolute_url(self):
        """Returns the url to access a detail information for this trainer."""
        return reverse('trainer-detail', args=[str(self.id)])

    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'

    class Meta:
        db_table = '트레이너'
        verbose_name = '트레이너'
        verbose_name_plural = '트레이너'

    def delete(self, *args, **kwargs):
        if self.image:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.image.path))
        super(Trainer, self).delete(*args, **kwargs)


class Lecture(models.Model):
    """Model representing the lecture(but not a specific class)."""
    trainer = models.ForeignKey('Trainer', on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=20, verbose_name='강의명')
    summary = models.TextField(max_length=1000, verbose_name='강의 설명')

    def __str__(self):
        """String for representing the Model object."""
        return f'{ self.name }, { self.trainer }'

    def get_absolute_url(self):
        """Returns the url to access a detail information for this class."""
        return reverse('lecture-detail', args=[str(self.id)])

    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'

    class Meta:
        db_table = '강의'
        verbose_name = '강의'
        verbose_name_plural = '강의'


class LectureInstance(models.Model):
    """Model representing the lecture(but not a specific class)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this class.')
    lecture = models.ForeignKey('Lecture', on_delete=models.SET_NULL, null=True)
    start_date = models.DateField(null=True, blank=True)
    trainee = models.ManyToManyField(User)

    WEEKDAY_TABLE = (
        ('a', 'Monday'),
        ('b', 'Tuesday'),
        ('c', 'Wednesday'),
        ('d', 'Thursday'),
        ('e', 'Friday'),
        ('f', 'Saturday'),
        ('g', 'Sunday'),
    )

    weekday = models.CharField(
        max_length=1,
        choices=WEEKDAY_TABLE,
        blank=False,
        default='a',
        help_text='Class Day',
    )

    TIME_TABLE = (
        ('a', 'AM 9:00~ AM 10:00'),
        ('b', 'AM 10:00~ AM 11:00'),
        ('c', 'AM 11:00~ PM 12:00'),
        ('d', 'PM 12:00~ PM 1:00'),
        ('e', 'PM 1:00~ PM 2:00'),
        ('f', 'PM 2:00~ PM 3:00'),
        ('g', 'PM 3:00~ PM 4:00'),
        ('h', 'PM 4:00~ PM 5:00'),
        ('i', 'PM 5:00~ PM 6:00'),
        ('j', 'PM 6:00~ PM 7:00'),
        ('k', 'PM 7:00~ PM 8:00'),
        ('l', 'PM 8:00~ PM 9:00'),
        ('m', 'PM 9:00~ PM 10:00'),
    )

    time = models.CharField(
        max_length=1,
        choices=TIME_TABLE,
        blank=False,
        default='a',
        help_text='Class Time',
    )

    CLASS_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'Occupied'),
        ('a', 'Available'),
    )

    status = models.CharField(
        max_length=1,
        choices=CLASS_STATUS,
        blank=False,
        default='a',
        help_text='Class Availability',
    )

    class Meta:
        ordering = ['weekday', 'time']

    def __str__(self):
        """String for representing the Model object."""
        return f'{ self.lecture }, { self.weekday }, { self.time }'

trainer/forms.py
from django import forms
from .models import Trainer


class TrainerNewForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(TrainerNewForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = '이름'
        self.fields['name'].widget.attrs.update({
            'placeholder': '이름을 입력해주세요.',
            'class': 'form-control',
            'autofocus': True,
        })
        self.fields['genretext'].label = '분야'
        self.fields['genretext'].widget.attrs.update({
            'placeholder': '분야를 입력해주세요.(예- PT, 필라테스 등 띄어쓰기로 구분)',
            'class': 'form-control',
        })
        self.fields['address'].label = '지역'
        self.fields['address'].widget.attrs.update({
            'placeholder': '지역을 입력해주세요. (예- 서울시 동작구)',
            'class': 'form-control',
        })
        self.fields['place'].label = '장소'
        self.fields['place'].widget.attrs.update({
            'placeholder': '장소를 입력해주세요. (예- 홍길동체육관)',
            'class': 'form-control',
        })
        self.fields['tagtext'].label = 'Hashtag'
        self.fields['tagtext'].widget.attrs.update({
            'placeholder': '특징을 입력해주세요. (예 - #차분한 #열정적인, 띄어쓰기로 구분)',
            'class': 'form-control',
        })
        formcontrol = ['cert1', 'cert2', 'cert3', 'cert4', 'cert5', 'cert6', 'cert7', 'cert8', 'cert9', 'cert10']
        formcontrol += ['sns1', 'sns2', 'sns3', 'sns4', 'sns5']
        for field_name, field in self.fields.items():
            if field_name in formcontrol:
                field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Trainer
        fields = ['writer', 'name', 'genretext', 'address', 'place', 'tagtext', 'image', 'summary']
        fields += ['cert1', 'certimg1', 'cert2', 'certimg2', 'cert3', 'certimg3', 'cert4', 'certimg4',
                   'cert5', 'certimg5', 'cert6', 'certimg6', 'cert7', 'certimg7', 'cert8', 'certimg8',
                   'cert9', 'certimg9', 'cert10', 'certimg10']
        fields += ['sns1', 'sns2', 'sns3', 'sns4', 'sns5']

templates/trainer/lecture_detail.html
{% extends 'base.html' %}

{% block contents %}
<h1>{{ lecture.name }}</h1>

<p><strong>Trainer: </strong><a href="{% url 'trainer-detail' lecture.trainer.pk %}">{{ lecture.trainer }}</a></p>
<p><strong>Genre: </strong>{% for genre in lecture.genre.all %}{{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
<p><strong>Place: </strong>{% for gym in lecture.gym.all %}{{ gym }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
</p>
<p><strong>Comment: </strong>{{ lecture.summary }}</p>

<div style="margin-left:20px;margin-top:20px">
    <h4>Classes</h4>

    {% for class in lecture.lectureinstance_set.all %}
    <hr>
    <p class="{% if class.status == 'a' %}text-success{% elif class.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ class.get_status_display }}</p>
    <p><strong>Day&Time: </strong>{{ class.get_weekday_display }}, {{ class.get_time_display }}</p>
    {% endfor %}
</div>
{% endblock %}

templates/trainer/lecture_list.html
{% extends 'base.html' %}

{% block contents %}
<div align="center" style="padding: 30px">
    <h1>레슨 신청 페이지 <small>(작업중)</small></h1>
</div>
{% endblock %}

templates/trainer/lecture_list_bak.html
{% extends 'base.html' %}

{% block contents %}
<div align="center" style="padding: 30px">
<h1>Classes List</h1>
{% if lecture_list %}
<ul>
    {% for lecture in lecture_list %}
    <li>
        <a href="{{ lecture.get_absolute_url }}">{{ lecture }}</a> ({{ lecture.genre }}, {{ lecture.gym }})
    </li>
    {% endfor %}
</ul>
{% else %}
<p>There are no classes in PTin.</p>
{% endif %}
</div>
{% endblock %}

templates/trainer/lecture_list_by_trainer.html
{% extends "base.html" %}

{% block contents %}
<h1>Your Classes</h1>

{% if lecture_list %}
    <ul>
    
    {% for lecture in lecture_list %}
        <li>
            <a href="{% url 'lecture-detail' lecture.lecture.pk %}">{{ lecture.lecture }}</a>
        </li>
    {% endfor %}
    </ul>
    
{% else %}
    <p>There are no classes by you.</p>
{% endif %}
{% endblock %}

templates/trainer/lecture_list_by_user.html
{% extends "base.html" %}

{% block contents %}
<h1>Your Classes</h1>

{% if lectureinstance_list %}
    <ul>

    {% for lectureinst in lectureinstance_list %}
        <li>
            <a href="{% url 'lecture-detail' lectureinst.lecture.pk %}">{{ lectureinst.lecture }}</a>
        </li>
    {% endfor %}
    </ul>

{% else %}
    <p>There are no classes you are taking.</p>
{% endif %}
{% endblock %}

templates/trainer/trainer_list.html
{% extends 'base.html' %}

{% block contents %}
<center>
    {% if b %}
    <h1>검색 결과</h1>
    {% else %}
    <h1>트레이너 찾기</h1>
    {% endif %}
</center>

<div class="row justify-content-center">
    {% if trainer_list %}
    <div class="col-11">
        <div class="row">
            {% for trainer in trainer_list %}
                <div class="col-6 col-md-4">
                    <div class="card" style="margin-bottom: 10">
                        <a href="{{ trainer.get_absolute_url }}">
                            <div class="row my-3 justify-content-center" style="text-align: center">
                                {% if trainer.image %}
                                <img style="width: 70%; padding: 0; margin-bottom: 15px; border-radius: 20px" src="{{ trainer.image.url }}">
                                {% else %}
                                <img style="width: 70%; padding: 0; margin-bottom: 15px; border-radius: 20px" src="/static/img/profile.png">
                                {% endif %}
                                <p style="font-size: 20px">{{ trainer.name }}<small>({% for genre in trainer.genre.all %}{{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %})</small></p>
                                <p style="font-size: 15px; margin-bottom: 1">{{ trainer.place }}</p>
                                <p style="font-size: 10px">( {{ trainer.address }} )</p>
                                <p style="font-size: 8px">{% for hashtag in trainer.hashtag.all %}#{{ hashtag }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
                            </div>
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    {% else %}
        {% if b %}
        <p>검색 결과가 없습니다.</p>
        {% else %}
        <p>현재 등록된 트레이너가 없습니다.</p>
        {% endif %}
    {% endif %}
</div>


{% if is_paginated %}
<ul class="pagination justify-content-center" style="margin-top: 7px">
    {% if page_obj.has_previous %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}"
            tabindex="-1">이전</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1">이전</a>
    </li>
    {% endif %}

    {% for page in page_range %}
    <li class="page-item {% if page == page_obj.number %} activate {% endif %}">
        <a class="page-link" href="?page={{ page }}">{{ page }}</a>
    </li>
    {% endfor %}

    {% if page_obj.has_next %}
    <li class="page-item">
        <a class="page-link"
            href="?page={{ page_obj.next_page_number }}">다음</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#">다음</a>
    </li>
    {% endif %}
</ul>
{% endif %}



<br><br><br>
{% endblock %}

templates/trainer/trainer_mylist.html
{% extends "accounts/mypage_nav.html" %}

{% block contents2 %}
<center>
    {% if b %}
    <h1>검색 결과</h1>
    {% else %}
    <h1>트레이너 찾기</h1>
    {% endif %}
</center>

<div class="row justify-content-center">
    {% if trainer_list %}
    <div class="col-11">
        <div class="row">
            {% for trainer in trainer_list %}
                <div class="col-6 col-md-4">
                    <div class="card" style="margin-bottom: 10">
                        <a href="{{ trainer.get_absolute_url }}">
                            <div class="row my-3 justify-content-center" style="text-align: center">
                                {% if trainer.image %}
                                <img style="width: 70%; margin-bottom: 15px; border-radius: 20px" src="{{ trainer.image.url }}">
                                {% else %}
                                <img style="width: 70%; margin-bottom: 15px; border-radius: 20px" src="/static/img/profile.png">
                                {% endif %}
                                <p style="font-size: 20px">{{ trainer.name }}<small>({% for genre in trainer.genre.all %}{{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %})</small></p>
                                <p style="font-size: 15px; margin-bottom: 1">{{ trainer.place }}</p>
                                <p style="font-size: 10px">( {{ trainer.address }} )</p>
                                <p style="font-size: 8px">{% for hashtag in trainer.hashtag.all %}#{{ hashtag }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
                            </div>
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    {% else %}
        {% if b %}
        <p>검색 결과가 없습니다.</p>
        {% else %}
        <p>현재 등록된 트레이너가 없습니다.</p>
        {% endif %}
    {% endif %}
</div>


{% if is_paginated %}
<ul class="pagination justify-content-center" style="margin-top: 7px">
    {% if page_obj.has_previous %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}"
            tabindex="-1">이전</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1">이전</a>
    </li>
    {% endif %}

    {% for page in page_range %}
    <li class="page-item {% if page == page_obj.number %} activate {% endif %}">
        <a class="page-link" href="?page={{ page }}">{{ page }}</a>
    </li>
    {% endfor %}

    {% if page_obj.has_next %}
    <li class="page-item">
        <a class="page-link"
            href="?page={{ page_obj.next_page_number }}">다음</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#">다음</a>
    </li>
    {% endif %}
</ul>
{% endif %}



<br><br><br>
{% endblock %}

templates/trainer/trainer_new_bak.html
{% extends 'base.html' %}

{% block header %}
{% load static %}
<link href="{% static 'css/summernote-lite.css' %}" rel="stylesheet">
<script type="text/javascript" src="{% static 'js/summernote-lite.js' %}"></script>
<script type="text/javascript" src="{% static 'js/lang/summernote-ko-KR.js' %}"></script>
{% endblock %}

{% block contents %}
<form method="POST" action="" enctype="multipart/form-data" >
    {% csrf_token %}
    <p><strong>이름: </strong>{{ form.name }}</p>
    <p><strong>사진: </strong>{{ form.image }}</p>
    <input type="checkbox" id="imageChangeCheck" name="imageChange" style="display: none;">
    <p><strong>분야: </strong>{{ form.genretext }}</p>
    <p><strong>지역: </strong>{{ form.address }}</p>
    <p><strong>장소: </strong>{{ form.place }}</p>
    <p><strong>Hashtag: </strong>{{ form.tagtext }}</p>
<!--    <p><strong>사진: </strong>{{ form.upload_files }}</p>-->
<!--    <input type="checkbox" id="fileChangeCheck" name="fileChange" style="display: none;">-->
    <p><strong>summary:</strong></p>
    <textarea id="summernote" name="summary">{% if update %}{{ form.summary.value | safe }}{% endif %}</textarea>

    <p>{{ form.cert1 }}</p>
    <p>{{ form.certimg1 }}</p>
    <input type="checkbox" id="certimg1ChangeCheck" name="certimg1Change" style="display: none;">
    <p>{{ form.cert2 }}</p>
    <p>{{ form.certimg2 }}</p>
    <input type="checkbox" id="certimg2ChangeCheck" name="certimg2Change" style="display: none;">
    <p>{{ form.cert3 }}</p>
    <p>{{ form.certimg3 }}</p>
    <input type="checkbox" id="certimg3ChangeCheck" name="certimg3Change" style="display: none;">
    <p>{{ form.cert4 }}</p>
    <p>{{ form.certimg4 }}</p>
    <input type="checkbox" id="certimg4ChangeCheck" name="certimg4Change" style="display: none;">
    <p>{{ form.cert5 }}</p>
    <p>{{ form.certimg5 }}</p>
    <input type="checkbox" id="certimg5ChangeCheck" name="certimg5Change" style="display: none;">
    <p>{{ form.cert6 }}</p>
    <p>{{ form.certimg6 }}</p>
    <input type="checkbox" id="certimg6ChangeCheck" name="certimg6Change" style="display: none;">
    <p>{{ form.cert7 }}</p>
    <p>{{ form.certimg7 }}</p>
    <input type="checkbox" id="certimg7ChangeCheck" name="certimg7Change" style="display: none;">
    <p>{{ form.cert8 }}</p>
    <p>{{ form.certimg8 }}</p>
    <input type="checkbox" id="certimg8ChangeCheck" name="certimg8Change" style="display: none;">
    <p>{{ form.cert9 }}</p>
    <p>{{ form.certimg9 }}</p>
    <input type="checkbox" id="certimg9ChangeCheck" name="certimg9Change" style="display: none;">
    <p>{{ form.cert10 }}</p>
    <p>{{ form.certimg10 }}</p>
    <input type="checkbox" id="certimg10ChangeCheck" name="certimg10Change" style="display: none;">

    <p>{{ form.sns1 }}</p>
    <p>{{ form.sns2 }}</p>
    <p>{{ form.sns3 }}</p>
    <p>{{ form.sns4 }}</p>
    <p>{{ form.sns5 }}</p>



    {% if update %}
    <button id="write" type="submit" class="btn btn-primary">수정</button>
    {% else %}
    <button id="write" class="btn btn-primary" type="submit">등록</button>
    {% endif %}
</form>

<script>
$(document).ready(function() {
    $('#summernote').summernote({
        height: 500,
        minHeight: 500,
        maxHeight: 500,
        lang: 'ko-KR',

        toolbar: [
        ['style', ['style']],
        ['font', ['bold', 'underline', 'clear', 'fontsize']],
        ['color', ['color']],
        ['para', ['ul', 'ol', 'paragraph']],
        ['table', ['table']],
        ['insert', ['link', 'picture', 'video']]
        ]
    });
    $('.note-resizebar').css('display','none');
});
</script>
<script type="text/javascript">
    var checkUnload = true;
    $(window).on('beforeunload', function () {
        if (checkUnload) return "이 페이지를 벗어나면 작성된 내용은 저장되지 않습니다.";
    });
    $("#write").on("click", function () {
        checkUnload = false;
        $("submit").submit();
    });
</script>
{% if imagename %}
<script type = "text/javascript">
    $("#id_image").change(function() {
        if ($('#id_image').get(0).files.length == 1) {
            $('#image-clear_id').attr("checked", false)
        }
    });
    $("#id_certimg1").change(function() {
        if ($('#id_certimg1').get(0).files.length == 1) {
            $('#certimg1-clear_id').attr("checked", false)
        }
    });
    $("#id_certimg2").change(function() {
        if ($('#id_certimg2').get(0).files.length == 1) {
            $('#certimg2-clear_id').attr("checked", false)
        }
    });
    $("#id_certimg3").change(function() {
        if ($('#id_certimg3').get(0).files.length == 1) {
            $('#certimg3-clear_id').attr("checked", false)
        }
    });
    $("#id_certimg4").change(function() {
        if ($('#id_certimg4').get(0).files.length == 1) {
            $('#certimg4-clear_id').attr("checked", false)
        }
    });
    $("#id_certimg5").change(function() {
        if ($('#id_certimg5').get(0).files.length == 1) {
            $('#certimg5-clear_id').attr("checked", false)
        }
    });
    $("#id_certimg6").change(function() {
        if ($('#id_certimg6').get(0).files.length == 1) {
            $('#certimg6-clear_id').attr("checked", false)
        }
    });
    $("#id_certimg7").change(function() {
        if ($('#id_certimg7').get(0).files.length == 1) {
            $('#certimg7-clear_id').attr("checked", false)
        }
    });
    $("#id_certimg8").change(function() {
        if ($('#id_certimg8').get(0).files.length == 1) {
            $('#certimg8-clear_id').attr("checked", false)
        }
    });
    $("#id_certimg9").change(function() {
        if ($('#id_certimg9').get(0).files.length == 1) {
            $('#certimg9-clear_id').attr("checked", false)
        }
    });
    $("#id_certimg10").change(function() {
        if ($('#id_certimg10').get(0).files.length == 1) {
            $('#certimg10-clear_id').attr("checked", false)
        }
    });


    $('#write').click( function() {
        if($('#id_image').get(0).files.length == 1){
            $('#imageChangeCheck').attr("checked",true)
        }
        if($('#id_certimg1').get(0).files.length == 1){
            $('#certimg1ChangeCheck').attr("checked",true)
        }
        if($('#id_certimg2').get(0).files.length == 1){
            $('#certimg2ChangeCheck').attr("checked",true)
        }
        if($('#id_certimg3').get(0).files.length == 1){
            $('#certimg3ChangeCheck').attr("checked",true)
        }
        if($('#id_certimg4').get(0).files.length == 1){
            $('#certimg4ChangeCheck').attr("checked",true)
        }
        if($('#id_certimg5').get(0).files.length == 1){
            $('#certimg5ChangeCheck').attr("checked",true)
        }
        if($('#id_certimg6').get(0).files.length == 1){
            $('#certimg6ChangeCheck').attr("checked",true)
        }
        if($('#id_certimg7').get(0).files.length == 1){
            $('#certimg7ChangeCheck').attr("checked",true)
        }
        if($('#id_certimg8').get(0).files.length == 1){
            $('#certimg8ChangeCheck').attr("checked",true)
        }
        if($('#id_certimg9').get(0).files.length == 1){
            $('#certimg9ChangeCheck').attr("checked",true)
        }
        if($('#id_certimg10').get(0).files.length == 1){
            $('#certimg10ChangeCheck').attr("checked",true)
        }
    });

</script>
{% endif %}
{% endblock %}