PTin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('trainer.urls')),
    path('', include('accounts.urls')),
    path('', include('review.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# def protected_files(request, path, document_root=None):
#     messages.error(request, "접근 불가")
#     return redirect('/')
#
#
# urlpatterns += static(settings.MEDIA_URL, protected_files, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('accounts/agreement/', views.AgreementView.as_view(), name='agreement'),
    path('accounts/signup_t/', views.TrainerRegisterView.as_view(), name='signup_t'),
    path('accounts/signup/', views.TraineeRegisterView.as_view(), name='signup'),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.logout_view, name='logout'),
    path('accounts/mypage/', views.mypage, name='mypage'),
    path('accounts/recovery/id/', views.RecoveryIdView.as_view(), name='recovery_id'),
    path('accounts/recovery/id/find/', views.ajax_find_id_view, name='ajax_id'),
    path('accounts/mypage/password_change/', views.password_edit_view, name='password_change'),
    path('accounts/profile/', views.profile_view, name='profile'),
    path('accounts/profile/update/', views.profile_update_view, name='profile_update'),
    path('accounts/delete/', views.profile_delete_view, name='profile_delete'),
    path('accounts/registerauth/', views.register_success, name='register_success'),
    path('accounts/activate/<str:uid64>/<str:token>/', views.activate, name='activate'),
    path('accounts/recovery/pw/', views.RecoveryPwView.as_view(), name='recovery_pw'),
    path('accounts/recovery/pw/find/', views.ajax_find_pw_view, name='ajax_pw'),
    path('accounts/recovery/pw/auth/', views.auth_confirm_view, name='recovery_auth'),
    path('accounts/recovery/pw/reset/', views.auth_pw_reset_view, name='recovery_pw_reset'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from .choice import *


class UserManager(BaseUserManager):
    def create_user(self, user_id, password, email, hp, name, auth, **extra_fields):
        user = self.model(
            user_id=user_id,
            email=email,
            hp=hp,
            name=name,
            auth=auth,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, user_id, password, email=None, hp=None, name=None, auth=None):
        user = self.create_user(user_id, password, email, hp, name, auth)
        user.is_superuser = True
        user.is_staff = True
        user.is_admin = True
        user.level = 0
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    objects = UserManager()

    user_id = models.CharField(max_length=17, verbose_name="아이디", unique=True)
    password = models.CharField(max_length=256, verbose_name="비밀번호")
    email = models.EmailField(max_length=128, verbose_name="이메일", null=True, unique=True)
    hp = models.IntegerField(verbose_name="핸드폰번호", null=True, unique=True)
    name = models.CharField(max_length=8, verbose_name="이름", null=True)
    level = models.CharField(choices=LEVEL_CHOICES, max_length=18, verbose_name="등급", default=3)
    auth = models.CharField(max_length=10, verbose_name="인증번호", null=True)
    date_joined = models.DateTimeField(auto_now_add=True, verbose_name='가입일', null=True, blank=True)

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'user_id'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.user_id

    class Meta:
        db_table = "회원목록"
        verbose_name = "사용자"
        verbose_name_plural = "사용자"

accounts/views.py
from django.core.exceptions import PermissionDenied, ValidationError
from django.shortcuts import render
from django.contrib.auth import login, authenticate, logout, update_session_auth_hash
from django.utils.decorators import method_decorator
from .decorators import *
from django.views.generic import View, CreateView, FormView
from django.contrib import messages
from .forms import *
import json
from django.core.serializers.json import DjangoJSONEncoder
from django.urls import reverse
from .helper import send_mail, email_auth_num
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from django.contrib.auth.tokens import default_token_generator


@method_decorator(logout_message_required, name='dispatch')
class AgreementView(View):
    def get(self, request, *args, **kwargs):
        request.session['agreement'] = False
        return render(request, 'accounts/agreement.html')

    def post(self, request, *args, **kwargs):
        if request.POST.get('agreement1', False) and request.POST.get('agreement2', False):
            request.session['agreement'] = True

            # Check whether Trainer or Trainee register.
            if request.POST.get('signup_t') == 'signup_t':
                return redirect('/accounts/signup_t/')
            else:
                return redirect('/accounts/signup/')

        else:
            messages.info(request, "약관에 모두 동의해주세요.")
            return render(request, 'accounts/agreement.html')


class TrainerRegisterView(CreateView):
    model = User
    template_name = 'accounts/signup_t.html'
    form_class = TrainerRegisterForm

    def get(self, request, *args, **kwargs):
        if not request.session.get('agreement', False):
            raise PermissionDenied
        request.session['agreement'] = False
        return super().get(request, *args, **kwargs)

    def get_success_url(self):
        self.request.session['register_auth'] = True
        messages.success(self.request, "입력된 Email 주소로 인증 메일이 발송되었습니다.")
        return reverse('accounts:register_success')

    def form_valid(self, form):
        self.object = form.save()

        send_mail(
            '{}님의 회원가입 인증메일 입니다.'.format(self.object.user_id),
            [self.object.email],
            html=render_to_string('accounts/register_email.html', {
                'user': self.object,
                'uid': urlsafe_base64_encode(force_bytes(self.object.pk)).encode().decode(),
                'domain': self.request.META['HTTP_HOST'],
                'token': default_token_generator.make_token(self.object),
            })
        )
        return redirect(self.get_success_url())


class TraineeRegisterView(TrainerRegisterView):
    model = User
    template_name = 'accounts/signup.html'
    form_class = TraineeRegisterForm


def register_success(request):
    if not request.session.get('register_auth', False):
        raise PermissionDenied
    request.session['register_auth'] = False

    return render(request, 'accounts/register_success.html')


@method_decorator(logout_message_required, name='dispatch')
class LoginView(FormView):
    template_name = 'accounts/login.html'
    form_class = LoginForm
    success_url = '/'

    def form_valid(self, form):
        user_id = form.cleaned_data.get('user_id')
        password = form.cleaned_data.get('password')
        user = authenticate(self.request, username=user_id, password=password)

        if user is not None:
            self.request.session['user_id'] = user_id
            login(self.request, user)
            remember_session = self.request.POST.get('remember_session', False)
            if remember_session:
                settings.SESSION_EXPIRE_AT_BROWSER_CLOSE = False

        return super().form_valid(form)


def logout_view(request):
    logout(request)
    return redirect('/')


def mypage(request):
    return render(request, 'accounts/mypage.html')


@method_decorator(logout_message_required, name='dispatch')
class RecoveryIdView(View):
    template_name = 'accounts/recovery_id.html'
    form = RecoveryIdForm

    def get(self, request):
        if request.method == 'GET':
            # form = self.recovery_id(None)
            form = RecoveryIdForm
            return render(request, self.template_name, {'form': form})


def ajax_find_id_view(request):
    name = request.POST.get('name')
    email = request.POST.get('email')
    result_id = User.objects.get(name=name, email=email)

    return HttpResponse(json.dumps({"result_id": result_id.user_id}, cls=DjangoJSONEncoder),
                        content_type="application/json")


@login_message_required
def password_edit_view(request):
    if request.method == 'POST':
        password_change_form = CustomPasswordChangeForm
        if password_change_form.is_valid():
            user = password_change_form.save()
            update_session_auth_hash(request, user)
            messages.success(request, "비밀번호를 성공적으로 변경하셨습니다.")
            return redirect('accounts:mypage')
    else:
        password_change_form = CustomPasswordChangeForm(request.user)

    return render(request, 'accounts/password_change.html', {'password_change_form': password_change_form})


@login_message_required
def profile_view(request):
    if request.method == 'GET':
        return render(request, 'accounts/profile.html')


@login_message_required
def profile_update_view(request):
    if request.method == 'POST':
        user_change_form = TrainerChangeForm(request.POST, instance=request.user)

        if user_change_form.is_valid():
            user_change_form.save()
            messages.success(request, '회원정보가 수정되었습니다.')
            return render(request, 'user/profile.html')

    else:
        user_change_form = TrainerChangeForm(instance=request.user)

        return render(request, 'accounts/profile_update.html', {'user_change_form': user_change_form})


@login_message_required
def profile_update_view(request):
    if request.method == 'POST':
        user_change_form = TraineeChangeForm(request.POST, instance=request.user)

        if user_change_form.is_valid():
            user_change_form.save()
            messages.success(request, '회원정보가 수정되었습니다.')
            return render(request, 'accounts/profile.html')

    else:
        user_change_form = TraineeChangeForm(instance=request.user)

        return render(request, 'accounts/profile_update.html', {'user_change_form': user_change_form})


@login_message_required
def profile_delete_view(request):
    if request.method == 'POST':
        password_form = CheckPasswordForm(request.user, request.POST)

        if password_form.is_valid():
            request.user.delete()
            logout(request)
            messages.success(request, "회원탈퇴가 완료되었습니다.")
            return redirect('/accounts/login/')

    else:
        password_form = CheckPasswordForm(request.user)

    return render(request, 'accounts/profile_delete.html', {'password_form': password_form})


def activate(request, uid64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uid64))
        current_user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist, ValidationError):
        messages.error(request, '메일 인증에 실패했습니다.')
        return redirect('accounts:login')

    if default_token_generator.check_token(current_user, token):
        current_user.is_active = True
        current_user.save()

        messages.info(request, '메일 인증이 완료되었습니다. 회원가입을 축하드립니다!')
        return redirect('accounts:login')

    messages.error(request, '메일 인증에 실패했습니다.')
    return redirect('accounts:login')


@method_decorator(logout_message_required, name='dispatch')
class RecoveryPwView(View):
    template_name = 'accounts/recovery_pw.html'
    recovery_pw = RecoveryPwForm

    def get(self, request):
        if request.method == 'GET':
            form = self.recovery_pw(None)
            return render(request, self.template_name, {'form': form, })


def ajax_find_pw_view(request):
    user_id = request.POST.get('user_id')
    name = request.POST.get('name')
    email = request.POST.get('email')
    target_user = User.objects.get(user_id=user_id, name=name, email=email)

    if target_user:
        auth_num = email_auth_num()
        target_user.auth = auth_num
        target_user.save()

        send_mail(
            '비밀번호 찾기 인증메일입니다.',
            [email],
            html=render_to_string('accounts/recovery_email.html', {
                'auth_num': auth_num,
            })
        )
    return HttpResponse(json.dumps({ "result": target_user.user_id }, cls=DjangoJSONEncoder), content_type="application/json")


def auth_confirm_view(request):
    user_id = request.POST.get('user_id')
    input_auth_num = request.POST.get('input_auth_num')
    target_user = User.objects.get(user_id=user_id, auth=input_auth_num)
    target_user.auth = ""
    target_user.save()
    request.session['auth'] = target_user.user_id

    return HttpResponse(json.dumps({"result": target_user.user_id}, cls=DjangoJSONEncoder), content_type = "application/json")


@logout_message_required
def auth_pw_reset_view(request):
    if request.method == 'GET':
        if not request.session.get('auth', False):
            raise PermissionDenied

    if request.method == 'POST':
        session_user = request.session['auth']
        current_user = User.objects.get(user_id=session_user)
        login(request, current_user)

        reset_password_form = CustomSetPasswordForm(request.user, request.POST)

        if reset_password_form.is_valid():
            user = reset_password_form.save()
            messages.success(request, "비밀번호 변경완료! 변경된 비밀번호로 로그인하세요.")
            logout(request)
            return redirect('accounts:login')
        else:
            logout(request)
            request.session['auth'] = session_user

    else:

templates/accounts/agreement.html
{% extends "accounts/register_template.html" %}

{% block contents2 %}
<h3>약관1</h3>
<p>어쩌구저쩌구</p>
<form action="" method="POST">
    {% csrf_token %}
    <div>
        <label>
            <input type="checkbox" name="agreement1" />
            <span>이용약관에 동의합니다.</span>
        </label>
    </div>
    <p>&nbsp;</p>
    <h3>약관2</h3>
    <p>블라블라블라</p>
    <div>
        <label>
            <input type="checkbox" name="agreement2" />
            <span>개인정보 수집 및 이용에 동의합니다.</span>
         </label>
    </div>
    <p>&nbsp;</p>
    <div align="center">
        <button type="submit" name="signup_t" class="btn btn-primary" value="signup_t">Trainer</button>
        <button type="submit" name="signup" class="btn btn-primary" value="signup">Trainee</button>
    </div>
</form>
{% endblock %}

templates/accounts/logged_out.html
{% extends "base.html" %}

{% block contents %}
<p>Logged out!</p>
<p><a href="{% url 'login' %}">Click here to login again.</a></p>
{% endblock %}

<p><a href="{% url 'password_reset' %}">Lost password?</a></p>

templates/accounts/login.html
{% extends "accounts/register_template.html" %}

{% block contents2 %}
<form method="post" action="" novalidate>
    {% csrf_token %}
    <div style="margin-bottom: 10px">
        <label style="margin-bottom: 10px" name="label_user_id" for="{{ form.user_id.id_for_label }}">
            {{ form.user_id.label }}
        </label>
        {{ form.user_id }}
        <script type="text/javascript">
            if (document.getElementsByName('user_id')[0].value != '') {
                document.getElementsByName('label_user_id')[0].setAttribute('class', 'active');
            }
        </script>
        {% if form.user_id.errors %}
        <script type="text/javascript">
            document.getElementsByName('user_id')[0].setAttribute('class', 'form-control is-invalid')
        </script>
        {% for error in form.user_id.errors %}
        <div class="invalid-feedback">
            {{ error }}
        </div>
        {% endfor %}
        {% endif %}
    </div>
    <div style="margin-bottom: 10px">
        <label style="margin-bottom: 10px" name="label_password" for="{{ form.password.id_for_label }}">
            {{ form.password.label }}
        </label>
        {{ form.password }}
        {% if form.password.errors %}
        <script type="text/javascript">
            document.getElementsByName('password')[0].setAttribute('class', 'form-control is-invalid')
        </script>
        {% for error in form.password.errors %}
        <div class="invalid-feedback">
            {{ error }}
        </div>
        {% endfor %}
        {% endif %}
    </div>
    <div class="row">
        <div class="col-8">
            <label>
                <input type="checkbox" name="remember_session"/>
                <span>로그인 상태 유지</span>
            </label>
        </div>
        <div class="col-4" align="right">
            <input type="submit" class="btn btn-outline-secondary" value="로그인">
        </div>
    </div>
</form>
<div align="center">
<a href="{% url 'accounts:recovery_id' %}"><button class="btn btn-outline-secondary">아이디찾기</button></a>
<a href="{% url 'accounts:recovery_pw' %}"><button class="btn btn-outline-secondary">비밀번호찾기</button></a>
</div>
{% endblock %}

templates/accounts/mypage.html
{% extends "accounts/mypage_nav.html" %}

{% block contents2 %}
<h1>My Page</h1>
{% endblock %}

templates/accounts/mypage_nav.html
{% extends "base.html" %}

{% block header %}
{% block header2 %}
{% endblock %}
{% endblock %}

{% block contents %}
<div class="row">
    <div class="col-4 col-md-3" style="padding-left: 20px">
        <p>&nbsp;</p>
        <p><a href="{% url 'accounts:profile' %}">회원정보</a></p>
        <p><a href="{% url 'accounts:password_change' %}">비밀번호 변경</a></p>
        {% if request.user.level == '0' or request.user.level == '1' or request.user.level == '2' %}
        <p><a href="{% url 'trainer-new' %}">트레이너 정보 등록</a></p>
        <p><a href="{% url 'trainer-mylist' %}">트레이너 정보 수정</a></p>
        {% endif %}
        <p><a href="{% url 'accounts:profile_delete' %}">회원 탈퇴</a></p>
    </div>
    <div class="col-8 col-md-9" style="padding: 40 60 0 10">
        <div class="row">
            <div class="register_template col-12 col-md-11" style="padding: 40; border-radius: 5px; background-color: #F8F8F8;">
                {% block contents2 %}{% endblock %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/accounts/password_change.html
{% extends 'accounts/mypage_nav.html' %}

{% block contents2 %}
<form method="POST" novalidate>
    {% csrf_token %}
    <div>
        <label name="label_old_password" for="{{ password_change_form.old_password.id_for_label }}">{{ password_change_form.old_password.label }}</label>
        {{ password_change_form.old_password }}
        <script type="text/javascript">
            if (document.getElementsByName('old_password')[0].value != '') {
                document.getElementsByName('label_old_password')[0].setAttribute('class', 'active');
            }
        </script>
        {% if password_change_form.old_password.errors %}
        <script type="text/javascript">
            document.getElementsByName('old_password')[0].setAttribute('class', 'form-control is-invalid')
        </script>
        {% for error in password_change_form.old_password.errors %}
        <div class="invalid-feedback">
            {{ error }}
        </div>
        {% endfor %}
        {% endif %}
    </div>
    <div>
        <label name="label_new_password1" for="{{ password_change_form.new_password1.id_for_label }}">{{ password_change_form.new_password1.label }}</label>
        {{ password_change_form.new_password1 }}
        <script type="text/javascript">
            if (document.getElementsByName('new_password1')[0].value != '') {
                document.getElementsByName('label_new_password1')[0].setAttribute('class', 'active');
            }
        </script>
        {% if password_change_form.new_password1.errors %}
        <script type="text/javascript">
            document.getElementsByName('new_password1')[0].setAttribute('class', 'form-control is-invalid')
        </script>
        {% for error in password_change_form.new_password1.errors %}
        <div class="invalid-feedback">
            {{ error }}
        </div>
        {% endfor %}
        {% endif %}
    </div>
    <div>
        <label name="label_new_password2" for="{{ password_change_form.new_password2.id_for_label }}">{{ password_change_form.new_password2.label }}</label>
        {{ password_change_form.new_password2 }}
        <script type="text/javascript">
            if (document.getElementsByName('new_password2')[0].value != '') {
                document.getElementsByName('label_new_password2')[0].setAttribute('class', 'active');
            }
        </script>
        {% if password_change_form.new_password2.errors %}
        <script type="text/javascript">
            document.getElementsByName('new_password2')[0].setAttribute('class', 'form-control is-invalid')
        </script>
        {% for error in password_change_form.new_password2.errors %}
        <div style="white-space: nowrap;" class="invalid-feedback">
            {{ error }}
        </div>
        {% endfor %}
        {% endif %}
        <small>
            최소 8개의 숫자와 문자 또는 특수기호를 입력해주세요.
        </small>
    </div>
    <div>
        <input type="submit" value="변경하기" class="btn btn-primary btn-sm">
    </div>
</form>
{% endblock %}

templates/accounts/password_reset.html
{% extends 'base.html' %}

{% block contents %}
<form action="" method="POST" novalidate>
    {% csrf_token %}
    <div class="mb-4 md-form">
        <label name="label_new_password1" for="{{ form.new_password1.id_for_label }}"><i
                class="fas fa-unlock"></i>&nbsp;&nbsp;{{ form.new_password1.label }}</label>
        {{ form.new_password1 }}
        <script type="text/javascript">
            if (document.getElementsByName('new_password1')[0].value != '') {
                document.getElementsByName('label_new_password1')[0].setAttribute('class',
                    'active');
            }
        </script>
        {% if form.new_password1.errors %}
        <script type="text/javascript">
            document.getElementsByName('new_password1')[0].setAttribute('class',
                'form-control is-invalid')
        </script>
        {% for error in form.new_password1.errors %}
        <div class="invalid-feedback">
            {{ error }}
        </div>
        {% endfor %}
        {% endif %}
    </div>
    <div class="mb-4 md-form">
        <label name="label_new_password2" for="{{ form.new_password2.id_for_label }}"><i
                class="fas fa-unlock-alt"></i>&nbsp;&nbsp;{{ form.new_password2.label }}</label>
        {{ form.new_password2 }}
        <script type="text/javascript">
            if (document.getElementsByName('new_password2')[0].value != '') {
                document.getElementsByName('label_new_password2')[0].setAttribute('class',
                    'active');
            }
        </script>
        {% if form.new_password2.errors %}
        <script type="text/javascript">
            document.getElementsByName('new_password2')[0].setAttribute('class',
                'form-control is-invalid')
        </script>
        {% for error in form.new_password2.errors %}
        <div style="white-space: nowrap;" class="invalid-feedback">
            {{ error }}
        </div>
        {% endfor %}
        {% endif %}
        <small style="margin-left: 4px; margin-top:8px;" class="form-text text-muted">
            최소 8개의 숫자와 문자 또는 특수기호를 입력해주세요.
        </small>
    </div>
    <div style="padding-top:10px;" class="row justify-content-md-center">
        <button class="btn btn-red" style="opacity: 90%; font-size: 16px;"><i class="fas fa-check"></i>&nbsp;&nbsp;저장하기</button>
    </div>
</form>
{% endblock %}

templates/accounts/profile.html
{% extends 'accounts/mypage_nav.html' %}

{% block contents2 %}

<table>
    <tr>
        <td>아이디</td>
        {% if user.level == '0' %}
        <td>{{ user.user_id }}(개발자)</td>
        {% elif user.level == '1' %}
        <td>{{ user.user_id }}(관리자)</td>
        {% else %}
        <td>{{ user.user_id }}</td>
        {% endif %}
    </tr>
    <tr>
        <td style="width: 130">이메일</td>
        <td>{{ user.email }}</td>
    </tr>
    <tr>
        <td>이름</td>
        <td>{{ user.name }}</td>
    </tr>
    <tr>
        <td>hp</td>
        <td>0{{ user.hp }}</td>
    </tr>
    <tr>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td></td>
        <td><a href="{% url 'accounts:profile_update' %}"><button class="btn btn-outline-secondary">회원정보 수정</button></a></td>
    </tr>
</table>
{% endblock %}

templates/accounts/recovery_pw.html
{% extends "accounts/register_template.html" %}

{% block contents2 %}
<div>
    {% csrf_token %}
    <div style="margin-bottom: 10px">
        <label style="margin-bottom: 10px" name="label_user_id" for="{{ form.user_id.id_for_label }}">{{ form.user_id.label }}</label>
        {{ form.user_id }}
    </div>
    <div style="margin-bottom: 10px">
        <label style="margin-bottom: 10px" name="label_name" for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
        {{ form.name }}
    </div>
    <div style="margin-bottom: 10px">
        <label style="margin-bottom: 10px" name="label_email" for="{{ form.email.id_for_label }}">{{ form.email.label }}</label>
            {{ form.email }}
        <small>
            등록하신 메일로 인증번호가 발송됩니다.
        </small>
    </div>
    <div align="center">
    <div id="div_find_pw">
        <button id="find_pw" class="btn btn-outline-secondary" name="recovery_pw">비밀번호찾기</button>
    </div>

    <div id="result_pw"></div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('#find_pw').click(function () {
            $('#loading').replaceWith('<div id="loading_end" class="loading"></div>')
            var user_id = $("#pw_form_id").val();
            var name = $("#pw_form_name").val();
            var email = $("#pw_form_email").val();

            $.ajax({
                type: "POST",
                url: "/accounts/recovery/pw/find/",
                dataType: "json",
                data: {
                    'user_id': user_id,
                    'name': name,
                    'email': email,
                    'csrfmiddlewaretoken': '{{csrf_token}}',
                },
                success: function (response) {
                    $('#loading_end').remove()
                    alert('회원님의 이메일로 인증코드를 발송하였습니다.');
                    // $('#result_pw').replaceWith('<h5><p id="result_pw">회원님의 비밀번호는 <strong>'+response.result_pw+'</strong> 입니다.</p></h5>')
                    $('#div_find_pw').remove()
                    $('#result_pw').replaceWith(
                        // '<br><form action="{% url "accounts:recovery_auth" %}" method="POST"><input type="text" name="input_auth_num" placeholder="인증번호를 입력해주세요." class="form-control" /><br><button type="submit" name="auth_confirm" class="btn btn-danger">인증확인</button></form>'
                        '<hr><div class="row justify-content-md-center"><form class="form-inline" style="margin-bottom:-15px; margin-top:-10px;"><div class="md-form md-outline"><label for="input_auth_num">인증번호 입력 (<span id="timeset"></span>)</label><input type="text" id="input_auth_num" class="form-control mx-sm-2" autofocus/></div></form>'+
                        '<button type="submit" name="auth_confirm" id="id_auth_confirm" class="btn btn-red" style="opacity: 90%; height:30%; margin-top:10px; font-size: 12px;"><i class="fas fa-check"></i>&nbsp;&nbsp;인증확인</button></div><hr>'
                    )
                    function countdown( elementName, minutes, seconds ) {
                        var elementName, endTime, hours, mins, msLeft, time;
                        function twoDigits( n ) {
                            return (n <= 9 ? "0" + n : n);
                        }
                        function updateTimer() {
                            msLeft = endTime - (+new Date);
                            if ( msLeft < 1000 ) {
                                alert("인증시간이 초과되었습니다.");
                                $("" + elementName).remove();
                                cert_ok = false;
                                certificationNum = false;
                                location.href = "{% url 'accounts:recovery_pw' %}"
                            } else {
                                time = new Date( msLeft );
                                hours = time.getUTCHours();
                                mins = time.getUTCMinutes();
                                $("" + elementName).html((hours ? hours + ':' + twoDigits( mins ) : twoDigits(mins))
                                + ':' + twoDigits( time.getUTCSeconds()));
                                setTimeout( updateTimer, time.getUTCMilliseconds() + 500 );
                            }
                        }
                        endTime = (+new Date) + 1000 * (60*minutes + seconds) + 500;
                        updateTimer();
                    }
                    countdown("#timeset", 5, 0);

                    var user = response.result

                    $(document).ready(function () {
                        $('#id_auth_confirm').click(function () {
                            var input_auth_num = $("#input_auth_num").val();

                            $.ajax({
                                type: "POST",
                                url: "/accounts/recovery/pw/auth/",
                                dataType: "json",
                                data: {
                                    'user_id': user,
                                    'input_auth_num': input_auth_num,
                                    'csrfmiddlewaretoken': '{{csrf_token}}',
                                },
                                success: function (response) {
                                    // location.href = "/accounts/profile/password/";
                                    location.href = "{% url 'accounts:recovery_pw_reset' %}";
                                },
                                error: function () {
                                    if ($('#input_auth_num').val()=="") {
                                        alert('회원님의 이메일로 전송된 인증번호를 입력해주세요.');
                                    } else {
                                        alert('인증번호가 일치하지 않습니다.');
                                    }
                                },
                            });
                        })
                    })
                },
                error: function () {
                    $('#loading_end').remove()
                    if (user_id == "" || name == "" || email == "") {
                        alert('아이디, 이름, 이메일을 모두 입력해주세요.');
                    } else {
                        alert('입력하신 정보가 일치하지 않거나 존재하지 않습니다.');
                    }
                },
            });
        })
    });
</script>
{% endblock %}

templates/accounts/register_success.html
{% extends "accounts/register_template.html" %}

{% block contents2 %}
<div align="center">
    <h4>인증 메일 발송이 완료되습니다.</h4>
</div>
{% endblock %}