PTin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('trainer.urls')),
    path('', include('accounts.urls')),
    path('', include('review.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# def protected_files(request, path, document_root=None):
#     messages.error(request, "접근 불가")
#     return redirect('/')
#
#
# urlpatterns += static(settings.MEDIA_URL, protected_files, document_root=settings.MEDIA_ROOT)

review/urls.py
from django.urls import path
from . import views

app_name = 'review'

urlpatterns = [
    path('review/', views.ReviewListView.as_view(), name='reviews'),
    path('review/<int:pk>', views.review_detail_view, name='review-detail'),
    path('review/new', views.review_new, name='review-new'),
    path('review/<int:review_id>/update', views.review_update, name='review-update'),
    path('review/<int:review_id>/delete', views.review_delete, name='review-delete'),
]

review/models.py
import uuid
from datetime import datetime
import re

from django.db import models
from django.urls import reverse

from PTin import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import Resize, ResizeToFill
from trainer.models import Trainer, Genre, Hashtag


def get_review_image_path(instance, filename):
    ymd_path = datetime.now().strftime('%Y/%m/%d')
    uuid_name = uuid.uuid4().hex
    return '/'.join(['review/', ymd_path, uuid_name])


class Review(models.Model):
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL, verbose_name='작성자')
    trainer = models.ForeignKey(Trainer, null=True, blank=True, on_delete=models.SET_NULL, verbose_name='트레이너')
    date = models.DateTimeField(auto_now_add=True, blank=False, verbose_name='작성일')
    genretext = models.CharField(max_length=200, null=True, blank=True)
    genre = models.ManyToManyField(Genre, blank=True, verbose_name='장르')
    tagtext = models.CharField(max_length=200, null=True, blank=True)
    hashtag = models.ManyToManyField(Hashtag, blank=True)
    title = models.CharField(max_length=100, null=True)
    content = models.TextField(null=True, blank=True)

    def hashtag_save(self):
        self.hashtag.set([])
        hashtags = re.findall(r'#(\w+)\b', str(self.tagtext))

        if not hashtags:
            return

        for tag in hashtags:
            tag, tag_created = Hashtag.objects.get_or_create(name=tag)
            self.hashtag.add(tag)

    def genre_save(self):
        self.genre.set([])
        genres = re.findall(r'(\w+)\b', str(self.genretext))

        if not genres:
            return

        for tag in genres:
            tag, tag_created = Genre.objects.get_or_create(name=tag)
            self.genre.add(tag)

    def __str__(self):
        """String for representing the Model object."""
        return str(self.id)

    def get_absolute_url(self):
        return reverse('review:review-detail', args=[str(self.id)])

    class Meta:
        db_table = '리뷰'
        verbose_name = '리뷰'
        verbose_name_plural = '리뷰'


class Photo(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE, null=True)
    image = ProcessedImageField(
        upload_to=get_review_image_path, processors=[ResizeToFill(width=640, height=720, upscale=False)],
        null=True, blank=True, format='JPEG', options={'quality': 90},
    )

    def __str__(self):
        return str(self.review)

review/forms.py
from django import forms
from .models import Review, Photo


class ReviewNewForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ReviewNewForm, self).__init__(*args, **kwargs)
        self.fields['title'].label = '제목'
        self.fields['title'].widget.attrs.update({
            'placeholder': '제목을 입력해주세요.',
            'class': 'form-control',
            'autofocus': True,
        })
        self.fields['genretext'].label = '분야'
        self.fields['genretext'].widget.attrs.update({
            'placeholder': '분야를 입력해주세요.(예- PT, 필라테스 등 띄어쓰기로 구분)',
            'class': 'form-control',
        })
        self.fields['tagtext'].label = 'Hashtag'
        self.fields['tagtext'].widget.attrs.update({
            'placeholder': '특징을 입력해주세요. (예 - #차분한 #열정적인, 띄어쓰기로 구분)',
            'class': 'form-control',
        })

    class Meta:
        model = Review
        fields = ['writer', 'trainer', 'title', 'genretext', 'tagtext', 'content']


class ImageUploadForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ['image']
        widgets = {
            'image': forms.ClearableFileInput(attrs={'multiple': True}),
        }

review/views.py
import os

from django.contrib import messages
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic

from .forms import ReviewNewForm, ImageUploadForm
from .models import Review, Photo
from accounts.decorators import login_message_required

from accounts.models import User
from trainer.models import Trainer

from PTin import settings


class ReviewListView(generic.ListView):
    model = Review
    paginate_by = 10
    template_name = 'review/review_list.html'
    context_object_name = 'review_list'

    def get_queryset(self):
        trainer_list = Review.objects.order_by('-id')
        self.request.session['trainer_id'] = None
        return trainer_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context['paginator']
        page_numbers_range = 5
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(page) if page else 1

        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range

        return context


def review_detail_view(request, pk):
    review = get_object_or_404(Review, pk=pk)

    # 접속자가 작성자와 일치하는지 확인
    if request.user == review.writer:
        review_auth = True
    else:
        review_auth = False

    context = {
        'review': review,
        'review_auth': review_auth,
    }
    return render(request, 'review/review_detail.html', context)


@login_message_required
def review_new(request):
    if request.method == "POST":
        form = ReviewNewForm(request.POST)
        imgform = ImageUploadForm(request.POST, request.FILES)
        user = request.session['user_id']
        trainer = request.session['trainer_id']
        trainer_name = request.session['trainer_name']
        user_id = User.objects.get(user_id=user)
        if trainer is None:
            pass
        else:
            trainer = Trainer.objects.filter(writer_id=trainer, name=trainer_name).first()

        if form.is_valid() and imgform.is_valid():
            review = form.save(commit=False)
            review.writer = user_id
            if trainer is None:
                pass
            else:
                review.trainer = trainer
            review.save()
            for img in request.FILES.getlist("image"):
                photo = Photo()
                photo.review = review
                photo.image = img
                photo.save()
            review.hashtag_save()
            review.genre_save()
            return redirect('review:review-detail', review.id)
    else:
        form = ReviewNewForm()
        imgform = ImageUploadForm()
    return render(request, 'review/review_new.html', {'form': form, 'imgform': imgform})


@login_message_required
def review_update(request, review_id):
    review = Review.objects.get(id=review_id)
    # image = Photo.objects.get(review=review)
    if request.method == "POST":
        if review.writer == request.user or request.user.level == '0':
            reviewimg_change_check = request.POST.get('reviewimgChange', False)
            reviewimg_check = request.POST.get('reviewimg-clear', False)
            if reviewimg_check or reviewimg_change_check:
                for image in review.photo_set.all():
                    os.remove(os.path.join(settings.MEDIA_ROOT, image.image.path))
                    image.delete()
            form = ReviewNewForm(request.POST, instance=review)
            imgform = ImageUploadForm(request.POST, request.FILES)

            writer = review.writer
            trainer = review.trainer
            if form.is_valid() and imgform.is_valid():
                review = form.save(commit=False)
                review.writer = writer
                review.trainer = trainer
                review.save()
                for img in request.FILES.getlist("image"):
                    photo = Photo()
                    photo.review = review
                    photo.image = img
                    photo.save()
                review.hashtag_save()
                review.genre_save()
                messages.success(request, "수정되었습니다.")
                return redirect('review:review-detail', review.id)
    else:
        review = Review.objects.get(id=review_id)
        # image = Photo.objects.get(review=review)

        if review.writer == request.user or request.user.level == '0':
            form = ReviewNewForm(instance=review)
            imgform = ImageUploadForm()
            context = {
                'form': form,
                'update': '수정하기',
                'imgform': imgform
            }
            return render(request, "review/review_new.html", context)
        else:
            messages.error(request, "본인 게시글만 수정할 수 있습니다.")
            return redirect('review-detail', review.id)


@login_message_required
def review_delete(request, review_id):
    review = Review.objects.get(id=review_id)
    if review.writer == request.user or request.user.level =='0':
        review.delete()
        messages.success(request, "삭제되었습니다.")
        return redirect('review:reviews')
    else:
        messages.error(request, "본인 게시글만 삭제할 수 있습니다.")
    return redirect('review-detail', review.id)

templates/review/review_detail.html
{% extends 'base.html' %}

{% block contents %}
<h1 align="center">고객 후기</h1>
<div class="row justify-content-center" style="margin: 30px; background-color: #F8F8F8; border-radius: 20px; border: 1px solid #E6E6E6">
    <div class="col-12 col-md-10">
        <p>&nbsp;</p>
        <p style="font-size: 25">
            <span style="text-decoration: underline">
            {% if review.trainer %}
            {{ review.trainer.name }} ({{ review.trainer.writer }}) 트레이너
            {% else %}
            사이트 공통
            {% endif %}
            </span>
            <small>에 대한 리뷰입니다.</small>
        </p>
        <p><strong>작성자: </strong>{{ review.writer }}</p>
        <p><strong>분야: </strong>{% for genre in review.genre.all %}{{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
        <p><strong>특징: </strong>{% for tag in review.hashtag.all %}#{{ tag }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
        {% for photo in review.photo_set.all %}
        <img src="{{ photo.image.url }}" width="100">
        {% endfor %}
        <h5 style="margin-top: 15px">{{ review.title }}</h5>
        <p>{{ review.content | safe}}</p>
        <p>&nbsp;</p>
        {% if review_auth or request.user.level == '0' %}
        <a href="{% url 'review:review-update' review.id %}"><button class="btn btn-outline-secondary"><i class="fas fa-pencil-alt" style="color: gray"></i> 수정하기</button></a>
<!--        <a href="{% url 'review:review-delete' review.id %}"><button class="btn btn-secondary"><i class="far fa-trash-alt" style="color: gray"></i> 삭제하기</button></a>-->
        <button class="btn btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#delete_modal"><i class="far fa-trash-alt" style="color: gray"></i> 삭제하기</button>
        <!-- Modal -->
        <div id="delete_modal" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">삭제경고</h5>
<!--                        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">-->
<!--                            <span aria-hidden="true">&times;</span>-->
<!--                        </button>-->
                    </div>
                    <div class="modal-body">
                        <p>게시글을 삭제하시겠습니까?</p>
                        <p>삭제 후에는 자료를 복구할 수 없습니다.</p>
                    </div>
                    <div class="modal-footer">
                        <button onclick="delete_modal()" type="button" class="btn btn-dark">삭제하기</button>
                        <button type="button" class="btn btn-light" data-bs-dismiss="modal">취소하기</button>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        <p>&nbsp;</p>


    </div>
</div>


<script type="text/javascript">
    function delete_modal() {
        location.replace('/review/{{ review.id }}/delete');
    }
</script>
{% endblock %}

templates/review/review_list.html
{% extends 'base.html' %}

{% block contents %}
{% if b %}
<h1>검색 결과</h1>
{% else %}
<h1 align="center">고객 후기</h1>
{% endif %}

{% if b %}
<p></p>
{% else %}
<div style="text-align: right; padding-right: 35px">
    <a href="{% url 'review:review-new' %}"><button class="btn btn-outline-secondary"><i class="fas fa-pencil-alt" style="color: gray"></i> 리뷰쓰기</button></a>
</div>
{% endif %}

<div class="row justify-content-center" style="margin-top: 15; margin-bottom: 0">
    <div class="col-3 col-md-2 board-top">트레이너</div>
    <div class="col-6 col-md-5 board-top">제목</div>
    <div class="col-3 col-md-2 board-top">작성자</div>
    <div class="d-none d-md-block col-md-2 board-top">작성일</div>
</div>

{% if page_obj %}
    {% for review in page_obj %}
    <a href="{{ review.get_absolute_url }}">
        <div class="row justify-content-center">
            <div class="col-3 col-md-2 board-content" style="text-align: center">{% if review.trainer %}{{ review.trainer.name }}{% else %}공통{% endif %}</div>
            <div class="col-6 col-md-5 board-content" style="">{{ review.title }}</div>
            <div class="col-3 col-md-2 board-content" style="text-align: center">{{ review.writer }}</div>
            <div class="d-none d-md-block col-md-2 board-content" style="text-align: center">{{ review.date|date:"n월j일" }}</div>
        </div>
    </a>
    {% endfor %}
{% else %}
    {% if b %}
    <div class="row">
        <div class="col-12" style="text-align: center; margin-top: 50">
            <p>검색 결과가 없습니다.</p>
        </div>
    </div>
    {% else %}
    <div class="row">
        <div class="col-12" style="text-align: center; margin-top: 50">
            <p>아직 등록된 리뷰가 없습니다. 리뷰를 등록해보세요!</p>
        </div>
    </div>
    {% endif %}
{% endif %}

{% if is_paginated %}
<ul class="pagination justify-content-center" style="margin-top: 15px">
    {% if page_obj.has_previous %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}"
            tabindex="-1">이전</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1">이전</a>
    </li>
    {% endif %}

    {% for page in page_range %}
    <li class="page-item {% if page == page_obj.number %} activate {% endif %}">
        <a class="page-link" href="?page={{ page }}">{{ page }}</a>
    </li>
    {% endfor %}

    {% if page_obj.has_next %}
    <li class="page-item">
        <a class="page-link"
            href="?page={{ page_obj.next_page_number }}">다음</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#">다음</a>
    </li>
    {% endif %}
</ul>
{% endif %}

{% endblock %}

templates/review/review_new.html
{% extends 'base.html' %}

{% block header %}
{% load static %}
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.js"></script>
<script type="text/javascript" src="/static/js/lang/summernote-ko-KR.js"></script>
{% endblock %}

{% block contents %}
<form method="POST" action="" enctype="multipart/form-data" >
    {% csrf_token %}
    <div class="row justify-content-center">
        <div class="col-12 col-md-10">
            <p><strong>제목: </strong>{{ form.title }}</p>
            <p><strong>분야: </strong>{{ form.genretext }}</p>
            <p><strong>Hashtag: </strong>{{ form.tagtext }}</p>
            <p><strong>사진: </strong>{{ imgform.image }}</p>
            <input type="checkbox" id="reviewimgChangeCheck" name="reviewimgChange" style="display: none;">
            <p><strong>내용:</strong></p>
            <textarea id="summernote" name="content">{% if update %}{{ form.content.value | safe }}{% endif %}</textarea>
            {% if update %}
            <button id="write" type="submit" class="btn btn-primary">수정</button>
            {% else %}
            <button id="write" class="btn btn-primary" type="submit">등록</button>
            {% endif %}
        </div>
    </div>

</form>
<script>
$(document).ready(function() {
    $('#summernote').summernote({
        height: 500,
        minHeight: 500,
        maxHeight: 500,
        lang: 'ko-KR',

        toolbar: [
        ['style', ['style']],
        ['font', ['bold', 'underline', 'clear']],
        ['color', ['color']],
        ['para', ['ul', 'ol', 'paragraph']],
        ['table', ['table']],
        ['insert', ['link', 'picture', 'video']],
        ['view', ['fullscreen', 'help']]
        ]
    });
    $('.note-resizebar').css('display','none');
});
</script>
<script type="text/javascript">
    var checkUnload = true;
    $(window).on('beforeunload', function () {
        if (checkUnload) return "이 페이지를 벗어나면 작성된 내용은 저장되지 않습니다.";
    });
    $("#write").on("click", function () {
        checkUnload = false;
        $("submit").submit();
    });
</script>
<script type = "text/javascript">
    $("#id_image").change(function() {
        if ($('#id_image').get(0).files.length >= 1) {
            $('#reviewimg-clear_id').attr("checked", false)
        }
    });

    $('#write').click( function() {
        if($('#id_image').get(0).files.length >= 1){
            $('#reviewimgChangeCheck').attr("checked",true)
        }
    });
</script>
{% endblock %}