PTin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('trainer.urls')),
    path('', include('accounts.urls')),
    path('', include('review.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# def protected_files(request, path, document_root=None):
#     messages.error(request, "접근 불가")
#     return redirect('/')
#
#
# urlpatterns += static(settings.MEDIA_URL, protected_files, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('accounts/agreement/', views.AgreementView.as_view(), name='agreement'),
    path('accounts/signup_t/', views.TrainerRegisterView.as_view(), name='signup_t'),
    path('accounts/signup/', views.TraineeRegisterView.as_view(), name='signup'),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.logout_view, name='logout'),
    path('accounts/mypage/', views.mypage, name='mypage'),
    path('accounts/recovery/id/', views.RecoveryIdView.as_view(), name='recovery_id'),
    path('accounts/recovery/id/find/', views.ajax_find_id_view, name='ajax_id'),
    path('accounts/mypage/password_change/', views.password_edit_view, name='password_change'),
    path('accounts/profile/', views.profile_view, name='profile'),
    path('accounts/profile/update/', views.profile_update_view, name='profile_update'),
    path('accounts/delete/', views.profile_delete_view, name='profile_delete'),
    path('accounts/registerauth/', views.register_success, name='register_success'),
    path('accounts/activate/<str:uid64>/<str:token>/', views.activate, name='activate'),
    path('accounts/recovery/pw/', views.RecoveryPwView.as_view(), name='recovery_pw'),
    path('accounts/recovery/pw/find/', views.ajax_find_pw_view, name='ajax_pw'),
    path('accounts/recovery/pw/auth/', views.auth_confirm_view, name='recovery_auth'),
    path('accounts/recovery/pw/reset/', views.auth_pw_reset_view, name='recovery_pw_reset'),
]

review/urls.py
from django.urls import path
from . import views

app_name = 'review'

urlpatterns = [
    path('review/', views.ReviewListView.as_view(), name='reviews'),
    path('review/<int:pk>', views.review_detail_view, name='review-detail'),
    path('review/new', views.review_new, name='review-new'),
    path('review/<int:review_id>/update', views.review_update, name='review-update'),
    path('review/<int:review_id>/delete', views.review_delete, name='review-delete'),
]

templates/aboutus.html
{% extends 'base.html' %}

{% block contents %}
<div align="center">
    <p>&nbsp;</p>
    <h3><strong>ACT:AGORA</strong>는</h3>
    <p>&nbsp;</p>
    <h3>
        당신 주변에서<br>
        <strong>당신에게 필요한<br>
        능력과 자격을 갖춘</strong><br>
        트레이너를<br>
        소개하는 서비스입니다.
    </h3>
    <p>&nbsp;</p>
    <h3>
        ACT:AGORA에서<br>
        제공하는 정보로<br>
        트레이너의<br>
        <strong>능력과 비용을<br>
        객관적으로<br>
        비교할 수 있습니다.</strong>
    </h3>
    <p>&nbsp;</p>
    <h3>
        이 과정을 통해<br>
        본인에게 가장 적합한<br>
        트레이너를<br>
        선택 & 소개받을 수 있습니다.
    </h3>
    <p>&nbsp;</p>
    <h3>
        어렵고 복잡한 스포츠 자격증과<br>
        자질, 자격이 의심되는 트레이너 등<br>
        기존에 트레이닝을<br>
        받으실 때 겪었던<br>
        어려움을 해결합니다.
    </h3>
    <br><br>
</div>
{% endblock %}

templates/base.html
<html>
{% load static %}
    <head>
        <meta charset="utf-8">
        <meta name = "viewport" content = "width = device-width, initial-scale = 1"/>
<!--        <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>-->
<!--        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">-->
        <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
        <script src="{% static 'js/bootstrap.js' %}"></script>
        <script src="https://kit.fontawesome.com/c5df104f7a.js" crossorigin="anonymous"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}?ver=17" />
        <title>Act:Agora</title>
        {% block header %}{% endblock %}
    </head>

    <body>
    {% load has_group %}
        <div class="container-fluid" style="background-color: #E7E7E7">
            <div class="container">
                <div class="row">
                    <div id="top-logo" class="col-4 col-md-3">
                        <a href="{% url 'index' %}"><img class="img-fluid" src="{% static 'img/main-logo.png' %}" style="vertical-align: middle; max-height: 80px"></a>
                    </div>
                    <div id="top-userinfo" class="col-8 col-md-3 order-md-2" align="right" style="margin: auto; font-size: 13px">
                        {% if user.is_authenticated %}
                            환영합니다, {{ user.get_username }} 님<br>
                            <a href="{% url 'accounts:logout' %}"><button class="btn btn-primary btn-sm">Logout</button></a>
                            &nbsp;<a href="{% url 'accounts:mypage' %}"><button class="btn btn-primary btn-sm">My Page</button></button></a>
                        {% else %}
                            <a  href="{% url 'accounts:login' %}?next={{ request.path }}"><button class="btn btn-primary btn-sm">Login</button></a>
                            &nbsp;<a href="{% url 'accounts:agreement' %}"><button class="btn btn-primary btn-sm">Sign Up</button></a>
                        {% endif %}
                    </div>
                    <div id="top-search" class="col-12 col-md-6 order-md-1">
                        <form class="form my-1 my-md-4" action="{% url 'search' %}" method="GET" style="border-radius: 17px; background-color: white; text-align: center">
                            <input class="form my-1" style="height: 30px; width: 70%; vertical-align: middle" type="text" placeholder="Search" aria-label="Search" name="b" value="{{b}}">
                            <input type="submit" value="검색!" class="btn btn-light btn-sm">
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div id="top-menu-bg" class="container-fluid">
            <div class="container">
                <div class="row">
                    <div class="top-menu-btn col-sm-3 col-3" align="center"><a href="{% url 'aboutus' %}"><button class="btn btn-sm">About Us</button></a></div>
                    <div class="top-menu-btn col-sm-3 col-3" align="center"><a href="{% url 'trainers' %}"><button class="btn btn-sm">트레이너 정보</button></a></div>
                    <div class="top-menu-btn col-sm-3 col-3" align="center"><a href="{% url 'lectures' %}"><button class="btn btn-sm">레슨 신청</button></a></div>
                    <div class="top-menu-btn col-sm-3 col-3" align="center"><a href="{% url 'review:reviews' %}"><button class="btn btn-sm">고객 후기</button></a></div>
                </div>
            </div>
        </div>
        <div class="container-fluid" style="background-color: #F8F8F8">
            <div class="container" style="background-color: white; padding: 0px">
                <div class="row">
                    <div class="col-sm-12 col-12">
                        {% block contents %}{% endblock %}

                        {% if messages %}
                        {% for message in messages %}
                        {% if message.tags %}
                        <script>
                            alert("{{ message.message }}")
                        </script>
                        {% endif %}
                        {% endfor %}
                        {% endif %}
                        <p>&nbsp;</p>
                        <p>&nbsp;</p>
                        <p>&nbsp;</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="container-fluid">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <button class="btn">이용약관</button> <button class="btn">개인정보보호정책</button> <button class="btn">공지사항</button> <button class="btn">고객센터</button>
                    </div>
                    <div class="col-12">
                        <h4>010-1234-5678 <small>(평일 09:00 ~ 17:00)</small></h4>
                    </div>
                    <div class="col-12">
                        Act:Agora<br>
                        우리가 누군지 물으신다면...<br>
                        대답해드리는게 인지상정
                    </div>
                </div>
            </div>
        </div>
    <a style="display:scroll;position:fixed;bottom:10px;right:50%;" href="#" title=”top"><button class="btn btn-sm btn-outline-secondary"><i class="fas fa-caret-up" style="margin: 0; padding: 0"></i><br><span style="margin: 0; padding: 0">TOP</span></button></a>
    </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block contents %}
<div align="center">
    <h1 class="text-muted">혼자하니</h1>
    <h1 class="text-muted">지루하고</h1>
    <h1 class="text-muted">어려운</h1>
    <h1 class="text-muted">운동</h1>
    <h1 class="text-muted">...</h1>
    <h1 class="text-muted">이제는</h1>
    <h1><strong>제대로된 트레이너에게</strong></h1>
    <h1><strong>제대로 배우자!</strong></h1>
    <p>&nbsp;</p>
    <h5 class="text-muted">ACT:AGORA는<br>당신의 건강하고 재미있는<br>운동라이프를 응원합니다.</h5>
    <p>&nbsp;</p>
    <h7 class="text-muted">
        ACT:AGORA에는 현재 {{ num_trainers }}명의 트레이너들이 활동중입니다.
    </h7>


<!--<h1>Welcome to PTin!</h1>-->
<!--<p>Welcome to PTin, a website for matching the trainees to the trainers</p>-->
<!--<h2>Dynamic content</h2>-->
<!--<p>{{ num_trainers }} trainers have {{ num_instances }} classes in PTin.</p>-->
<!--<p>But there are only {{ num_instances_available }} classes left.</p>-->
</div>
{% endblock %}